"""Initial migration

Revision ID: 9d5883d72681
Revises: 
Create Date: 2025-05-20 20:37:46.840704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5883d72681'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.UUID(), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=False),
    sa.Column('api_category', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_id'), 'api', ['id'], unique=False)
    op.create_table('hub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('hub_id', sa.UUID(), nullable=True),
    sa.Column('parent_hub_name', sa.String(length=255), nullable=False),
    sa.Column('ref_parent_hub_name', sa.String(length=255), nullable=False),
    sa.Column('ref_parent_hub_id', sa.UUID(), nullable=False),
    sa.Column('hub_name', sa.String(length=255), nullable=False),
    sa.Column('hub_type', sa.String(length=255), nullable=False),
    sa.Column('ref_buhm_id', sa.UUID(), nullable=False),
    sa.Column('ref_buhm_name', sa.String(length=255), nullable=False),
    sa.Column('postal_address', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hub_id'), 'hub', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('ppod_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('ppod_intent_id', sa.UUID(), nullable=True),
    sa.Column('ppod_intent_name', sa.String(length=255), nullable=False),
    sa.Column('cpod_intent_id', sa.UUID(), nullable=True),
    sa.Column('ref_cpod_intent_id', sa.UUID(), nullable=False),
    sa.Column('ref_cpod_intent_name', sa.String(length=255), nullable=False),
    sa.Column('leaf_uplink_a_lag_ipv4_local', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_a_lag_ipv4_remote', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_a_lag_ipv4_subnet', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_a_lag_ipv6_local', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_a_lag_ipv6_remote', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_a_lag_ipv6_subnet', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_a_local_ethernet_interfaces', sa.Text(), nullable=True),
    sa.Column('leaf_uplink_a_remote_ethernet_interfaces', sa.Text(), nullable=True),
    sa.Column('leaf_uplink_a_remote_host', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_b_lag_ipv4_local', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_b_lag_ipv4_remote', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_b_lag_ipv4_subnet', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_b_lag_ipv6_local', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_b_lag_ipv6_remote', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_b_lag_ipv6_subnet', sa.String(length=255), nullable=True),
    sa.Column('leaf_uplink_b_local_ethernet_interfaces', sa.Text(), nullable=True),
    sa.Column('leaf_uplink_b_remote_ethernet_interfaces', sa.Text(), nullable=True),
    sa.Column('leaf_uplink_b_remote_host', sa.String(length=255), nullable=True),
    sa.Column('dhcp_servers_ipv4', sa.Text(), nullable=True),
    sa.Column('dhcp_servers_ipv6', sa.Text(), nullable=True),
    sa.Column('vault_cms_shared_secret_path', sa.String(length=255), nullable=True),
    sa.Column('vault_cms_shared_secret_last_updated', sa.String(length=255), nullable=True),
    sa.Column('vault_rip_key_path', sa.String(length=255), nullable=True),
    sa.Column('vault_rip_key_last_updated', sa.String(length=255), nullable=True),
    sa.Column('magg_connections_local_ethernet_interfaces', sa.Text(), nullable=True),
    sa.Column('magg_connections_remote_ethernet_interfaces', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_vrf_type', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_vrf_cpe_v4_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_vrf_cpe_v6_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_vrf_cm_v4_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_vrf_cm_v6_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_cm_scope_v4_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_cm_scope_v6_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_cpe_scope_v4_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_cpe_scope_v6_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_mta_scope_v4_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_mta_scope_v6_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_stb_scope_v6_net', sa.Text(), nullable=True),
    sa.Column('cust_ip_scope_config_an_resi_pd_scope_v6_net', sa.Text(), nullable=True),
    sa.Column('ref_scn_profile_id', sa.UUID(), nullable=True),
    sa.Column('ref_scn_profile_name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppod_intent_id'), 'ppod_intent', ['id'], unique=False)
    op.create_table('site_intent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=True),
    sa.Column('site_intent_id', sa.UUID(), nullable=True),
    sa.Column('site_intent_name', sa.String(length=255), nullable=False),
    sa.Column('ref_hub_name', sa.String(length=255), nullable=False),
    sa.Column('ref_hub_id', sa.UUID(), nullable=False),
    sa.Column('csv_ip_oob', sa.String(length=255), nullable=True),
    sa.Column('comcast_routable_ipv4', sa.Text(), nullable=True),
    sa.Column('comcast_routable_ipv6', sa.Text(), nullable=True),
    sa.Column('partner_internal_ipv4', sa.Text(), nullable=True),
    sa.Column('partner_internal_ipv6', sa.Text(), nullable=True),
    sa.Column('internet_routed_ipv4', sa.Text(), nullable=True),
    sa.Column('internet_routed_ipv6', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_intent_id'), 'site_intent', ['id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('transaction_status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='transactionstatus'), nullable=False),
    sa.Column('transaction_type', sa.Enum('SINGLE', 'BULK', name='transactiontype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_site_intent_id'), table_name='site_intent')
    op.drop_table('site_intent')
    op.drop_index(op.f('ix_ppod_intent_id'), table_name='ppod_intent')
    op.drop_table('ppod_intent')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_hub_id'), table_name='hub')
    op.drop_table('hub')
    op.drop_index(op.f('ix_api_id'), table_name='api')
    op.drop_table('api')
    # ### end Alembic commands ###
